### PR TITLE
fix missing cache generation on multiple call

### PR DESCRIPTION
**Pull request by itkg-sthibault**

### CODE REVIEW

**Comment by itkg-ppottie** [comment]
:+1:

**Comment by farkam** [comment]
:+1:

**Comment by clement-michelet** [comment]
This is not a good way of doing that.
You should :
- add a method argument to bypass the cache (default: false)
- or disable the loaded outside of the method by using the `setIsLoaded` setter.

**Comment by itkg-sthibault** [comment]
@clement-michelet 
i think you dont understand the bug...
if you call webservice 
http://sample.org/api/?param=1 the response is set in cache it is good

if on next page you call 
http://sample.org/api/?param=1  the response is load from cache good too
and after you call http://sample.org/api/?param=2 the response is not set in cache because the webservice don't reset the flag between two request of the same webservice.

where do you want to reset the flag ? in the cacheListener ?

**Comment by clement-michelet** [comment]
I think you don't understand your bug and how the cache works.

Your problem is not about calling the webservice multiple times but how the cache is managed.
You call multiple times with different request. @pdenis fixed something about cache key [here](https://github.com/itkg/consumer/commit/b2e47e334bb117c2e9d1ef42a2892b9a11779edd) few days ago . 

If you look closely how the key is generated, you will see that it's only the URI and the content (i.e without queryString). The cache key should use the query string to manage your case.

You're welcome !

**Comment by itkg-sthibault** [comment]
l'anglais ca marche pas et les commentaire pour expliquer les problème ca marche non plus 
donc tu m'appel et je t'expliquer pourquoi j'ai raison et pourquoi je vais merge cette correction :)

**Comment by pdenis** [comment]
Je passerai ma plus la modif dans le cacheListener car il est en charge de gérer le cache et que c'est à lui de maintenir l'état du service

**Comment by clement-michelet** [comment]
:purple_heart: :purple_heart: :purple_heart: :
Je te laisse merge ta PR comme un grand garçon.

**Pull request closed without merging**
